/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign_in` | `/sign_in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign_up` | `/sign_up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify_email` | `/verify_email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/recipe/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign_in` | `/sign_in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign_up` | `/sign_up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verify_email` | `/verify_email`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/recipe/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign_in${`?${string}` | `#${string}` | ''}` | `/sign_in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign_up${`?${string}` | `#${string}` | ''}` | `/sign_up${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verify_email${`?${string}` | `#${string}` | ''}` | `/verify_email${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorite${`?${string}` | `#${string}` | ''}` | `/favorite${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign_in` | `/sign_in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign_up` | `/sign_up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify_email` | `/verify_email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/recipe/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/recipe/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
